apiVersion: apps/v1
kind: Deployment
metadata:
  name: front_devops
spec:
  selector:
    matchLabels:
      app: front_devops
  replicas: 3
  template:
    metadata:
      labels:
        app: front_devops
    spec:
      containers:
      - name: front_devops
        image: eyadrihmi/front_devops:latest
        ports:
        - containerPort: 80
